--
-- ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
-- บ       D E S I G N   E N G I N E E R I N G            บDบSบ        บ
-- บ            S O F T W A R E                           ศอสอผ        บ
-- บ                                                                   บ
-- บ        QtAda - Ada to QT5 interface                               บ
-- บ                                                                   บ
-- บ        Author :  Leonid Dulman     2014                           บ
-- บ                                                                   บ
-- บ Copyright (C) 2014                                                บ
-- ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
--
--
--   This library is free software; you can redistribute it and/or modify  *
--   it under the terms of the GNU Library General Public License as       *
--   published by the Free Software Foundation; either version 3 of the    *
--   License, or (at your option) any later version.                       *

package Qt.QOpenGLGlobal is

subtype GLenum is Integer; 
type pGLenum is access all GLenum;

subtype GLenumRGB is Integer; 
type pGLenumRGB is access all GLenumRGB;

subtype GLuint is quint;
type pGLuint  is access all GLuint;

subtype GLint  is integer;
type pGLint is access all GLint;

subtype GLbitfield is quint;
type pGLbitfield is access all GLbitfield;

subtype GLboolean is boolean;
type pGLboolean is access all GLboolean;

subtype GLfloat  is Float;
type pGLfloat is access all GLfloat;

subtype GLclampf is Float;
type pGLclampf is access all GLclampf;

subtype GLclampd is Long_Float;
type pGLclampd is access all GLclampd;

subtype GLsizei is quint; 
type pGLsizei is access all GLsizei; 

subtype GLubyte is  Qt.Unsigned_Char;
type pGLubyte is access all GLubyte;

 GL_NONE                                         : constant := 0;
 GL_NO_ERROR                                     : constant := 0;
 GL_ZERO                                         : constant := 0;
 GL_FALSE                                        : constant := 0;
 GL_TRUE                                         : constant := 1;
 GL_ONE                                          : constant := 1;
 GL_POINTS                                       : constant := 16#0000#;
 GL_LINES                                        : constant := 16#0001#;
 GL_LINE_LOOP                                    : constant := 16#0002#;
 GL_LINE_STRIP                                   : constant := 16#0003#;
 GL_TRIANGLES                                    : constant := 16#0004#;
 GL_TRIANGLE_STRIP                               : constant := 16#0005#;
 GL_TRIANGLE_FAN                                 : constant := 16#0006#;
 GL_DEPTH_BUFFER_BIT                             : constant := 16#0100#;
 GL_NEVER                                        : constant := 16#0200#;
 GL_LESS                                         : constant := 16#0201#;
 GL_EQUAL                                        : constant := 16#0202#;
 GL_LEQUAL                                       : constant := 16#0203#;
 GL_GREATER                                      : constant := 16#0204#;
 GL_NOTEQUAL                                     : constant := 16#0205#;
 GL_GEQUAL                                       : constant := 16#0206#;
 GL_ALWAYS                                       : constant := 16#0207#;
 GL_SRC_COLOR                                    : constant := 16#0300#;
 GL_ONE_MINUS_SRC_COLOR                          : constant := 16#0301#;
 GL_SRC_ALPHA                                    : constant := 16#0302#;
 GL_ONE_MINUS_SRC_ALPHA                          : constant := 16#0303#;
 GL_DST_ALPHA                                    : constant := 16#0304#;
 GL_ONE_MINUS_DST_ALPHA                          : constant := 16#0305#;
 GL_DST_COLOR                                    : constant := 16#0306#;
 GL_ONE_MINUS_DST_COLOR                          : constant := 16#0307#;
 GL_SRC_ALPHA_SATURATE                           : constant := 16#0308#;
 GL_STENCIL_BUFFER_BIT                           : constant := 16#0400#;
 GL_FRONT                                        : constant := 16#0404#;
 GL_BACK                                         : constant := 16#0405#;
 GL_FRONT_AND_BACK                               : constant := 16#0408#;
 GL_INVALID_ENUM                                 : constant := 16#0500#;
 GL_INVALID_VALUE                                : constant := 16#0501#;
 GL_INVALID_OPERATION                            : constant := 16#0502#;
 GL_OUT_OF_MEMORY                                : constant := 16#0505#;
 GL_INVALID_FRAMEBUFFER_OPERATION                : constant := 16#0506#;
 GL_CW                                           : constant := 16#0900#;
 GL_CCW                                          : constant := 16#0901#;
 GL_LINE_WIDTH                                   : constant := 16#0B21#;
 GL_CULL_FACE                                    : constant := 16#0B44#;
 GL_CULL_FACE_MODE                               : constant := 16#0B45#;
 GL_FRONT_FACE                                   : constant := 16#0B46#;
 GL_DEPTH_RANGE                                  : constant := 16#0B70#;
 GL_DEPTH_TEST                                   : constant := 16#0B71#;
 GL_DEPTH_WRITEMASK                              : constant := 16#0B72#;
 GL_DEPTH_CLEAR_VALUE                            : constant := 16#0B73#;
 GL_DEPTH_FUNC                                   : constant := 16#0B74#;
 GL_STENCIL_TEST                                 : constant := 16#0B90#;
 GL_STENCIL_CLEAR_VALUE                          : constant := 16#0B91#;
 GL_STENCIL_FUNC                                 : constant := 16#0B92#;
 GL_STENCIL_VALUE_MASK                           : constant := 16#0B93#;
 GL_STENCIL_FAIL                                 : constant := 16#0B94#;
 GL_STENCIL_PASS_DEPTH_FAIL                      : constant := 16#0B95#;
 GL_STENCIL_PASS_DEPTH_PASS                      : constant := 16#0B96#;
 GL_STENCIL_REF                                  : constant := 16#0B97#;
 GL_STENCIL_WRITEMASK                            : constant := 16#0B98#;
 GL_VIEWPORT                                     : constant := 16#0BA2#;
 GL_DITHER                                       : constant := 16#0BD0#;
 GL_BLEND                                        : constant := 16#0BE2#;
 GL_SCISSOR_BOX                                  : constant := 16#0C10#;
 GL_SCISSOR_TEST                                 : constant := 16#0C11#;
 GL_COLOR_CLEAR_VALUE                            : constant := 16#0C22#;
 GL_COLOR_WRITEMASK                              : constant := 16#0C23#;
 GL_UNPACK_ALIGNMENT                             : constant := 16#0CF5#;
 GL_PACK_ALIGNMENT                               : constant := 16#0D05#;
 GL_MAX_TEXTURE_SIZE                             : constant := 16#0D33#;
 GL_MAX_VIEWPORT_DIMS                            : constant := 16#0D3A#;
 GL_SUBPIXEL_BITS                                : constant := 16#0D50#;
 GL_RED_BITS                                     : constant := 16#0D52#;
 GL_GREEN_BITS                                   : constant := 16#0D53#;
 GL_BLUE_BITS                                    : constant := 16#0D54#;
 GL_ALPHA_BITS                                   : constant := 16#0D55#;
 GL_DEPTH_BITS                                   : constant := 16#0D56#;
 GL_STENCIL_BITS                                 : constant := 16#0D57#;
 GL_TEXTURE_2D                                   : constant := 16#0DE1#;
 GL_DONT_CARE                                    : constant := 16#1100#;
 GL_FASTEST                                      : constant := 16#1101#;
 GL_NICEST                                       : constant := 16#1102#;
 GL_BYTE                                         : constant := 16#1400#;
 GL_UNSIGNED_BYTE                                : constant := 16#1401#;
 GL_SHORT                                        : constant := 16#1402#;
 GL_UNSIGNED_SHORT                               : constant := 16#1403#;
 GL_INT                                          : constant := 16#1404#;
 GL_UNSIGNED_INT                                 : constant := 16#1405#;
 GL_FLOAT                                        : constant := 16#1406#;
 GL_FIXED                                        : constant := 16#140C#;
 GL_INVERT                                       : constant := 16#150A#;
 GL_TEXTURE                                      : constant := 16#1702#;
 GL_STENCIL_INDEX                                : constant := 16#1901#;
 GL_DEPTH_COMPONENT                              : constant := 16#1902#;
 GL_ALPHA                                        : constant := 16#1906#;
 GL_RGB                                          : constant := 16#1907#;
 GL_RGBA                                         : constant := 16#1908#;
 GL_LUMINANCE                                    : constant := 16#1909#;
 GL_LUMINANCE_ALPHA                              : constant := 16#190A#;
 GL_KEEP                                         : constant := 16#1E00#;
 GL_REPLACE                                      : constant := 16#1E01#;
 GL_INCR                                         : constant := 16#1E02#;
 GL_DECR                                         : constant := 16#1E03#;
 GL_VENDOR                                       : constant := 16#1F00#;
 GL_RENDERER                                     : constant := 16#1F01#;
 GL_VERSION                                      : constant := 16#1F02#;
 GL_EXTENSIONS                                   : constant := 16#1F03#;
 GL_NEAREST                                      : constant := 16#2600#;
 GL_LINEAR                                       : constant := 16#2601#;
 GL_NEAREST_MIPMAP_NEAREST                       : constant := 16#2700#;
 GL_LINEAR_MIPMAP_NEAREST                        : constant := 16#2701#;
 GL_NEAREST_MIPMAP_LINEAR                        : constant := 16#2702#;
 GL_LINEAR_MIPMAP_LINEAR                         : constant := 16#2703#;
 GL_TEXTURE_MAG_FILTER                           : constant := 16#2800#;
 GL_TEXTURE_MIN_FILTER                           : constant := 16#2801#;
 GL_TEXTURE_WRAP_S                               : constant := 16#2802#;
 GL_TEXTURE_WRAP_T                               : constant := 16#2803#;
 GL_REPEAT                                       : constant := 16#2901#;
 GL_POLYGON_OFFSET_UNITS                         : constant := 16#2A00#;
 GL_COLOR_BUFFER_BIT                             : constant := 16#4000#;
 GL_CONSTANT_COLOR                               : constant := 16#8001#;
 GL_ONE_MINUS_CONSTANT_COLOR                     : constant := 16#8002#;
 GL_CONSTANT_ALPHA                               : constant := 16#8003#;
 GL_ONE_MINUS_CONSTANT_ALPHA                     : constant := 16#8004#;
 GL_BLEND_COLOR                                  : constant := 16#8005#;
 GL_FUNC_ADD                                     : constant := 16#8006#;
 GL_BLEND_EQUATION                               : constant := 16#8009#;
 GL_BLEND_EQUATION_RGB                           : constant := 16#8009#;
 GL_FUNC_SUBTRACT                                : constant := 16#800A#;
 GL_FUNC_REVERSE_SUBTRACT                        : constant := 16#800B#;
 GL_UNSIGNED_SHORT_4_4_4_4                       : constant := 16#8033#;
 GL_UNSIGNED_SHORT_5_5_5_1                       : constant := 16#8034#;
 GL_POLYGON_OFFSET_FILL                          : constant := 16#8037#;
 GL_POLYGON_OFFSET_FACTOR                        : constant := 16#8038#;
 GL_RGBA4                                        : constant := 16#8056#;
 GL_RGB5_A1                                      : constant := 16#8057#;
 GL_TEXTURE_BINDING_2D                           : constant := 16#8069#;
 GL_SAMPLE_ALPHA_TO_COVERAGE                     : constant := 16#809E#;
 GL_SAMPLE_COVERAGE                              : constant := 16#80A0#;
 GL_SAMPLE_BUFFERS                               : constant := 16#80A8#;
 GL_SAMPLES                                      : constant := 16#80A9#;
 GL_SAMPLE_COVERAGE_VALUE                        : constant := 16#80AA#;
 GL_SAMPLE_COVERAGE_INVERT                       : constant := 16#80AB#;
 GL_BLEND_DST_RGB                                : constant := 16#80C8#;
 GL_BLEND_SRC_RGB                                : constant := 16#80C9#;
 GL_BLEND_DST_ALPHA                              : constant := 16#80CA#;
 GL_BLEND_SRC_ALPHA                              : constant := 16#80CB#;
 GL_BGRA                                         : constant := 16#80E1#;
 GL_CLAMP_TO_EDGE                                : constant := 16#812F#;
 GL_GENERATE_MIPMAP_HINT                         : constant := 16#8192#;
 GL_DEPTH_COMPONENT16                            : constant := 16#81A5#;
 GL_UNSIGNED_SHORT_5_6_5                         : constant := 16#8363#;
 GL_MIRRORED_REPEAT                              : constant := 16#8370#;
 GL_ALIASED_POINT_SIZE_RANGE                     : constant := 16#846D#;
 GL_ALIASED_LINE_WIDTH_RANGE                     : constant := 16#846E#;
 GL_TEXTURE0                                     : constant := 16#84C0#;
 GL_TEXTURE1                                     : constant := 16#84C1#;
 GL_TEXTURE2                                     : constant := 16#84C2#;
 GL_TEXTURE3                                     : constant := 16#84C3#;
 GL_TEXTURE4                                     : constant := 16#84C4#;
 GL_TEXTURE5                                     : constant := 16#84C5#;
 GL_TEXTURE6                                     : constant := 16#84C6#;
 GL_TEXTURE7                                     : constant := 16#84C7#;
 GL_TEXTURE8                                     : constant := 16#84C8#;
 GL_TEXTURE9                                     : constant := 16#84C9#;
 GL_TEXTURE10                                    : constant := 16#84CA#;
 GL_TEXTURE11                                    : constant := 16#84CB#;
 GL_TEXTURE12                                    : constant := 16#84CC#;
 GL_TEXTURE13                                    : constant := 16#84CD#;
 GL_TEXTURE14                                    : constant := 16#84CE#;
 GL_TEXTURE15                                    : constant := 16#84CF#;
 GL_TEXTURE16                                    : constant := 16#84D0#;
 GL_TEXTURE17                                    : constant := 16#84D1#;
 GL_TEXTURE18                                    : constant := 16#84D2#;
 GL_TEXTURE19                                    : constant := 16#84D3#;
 GL_TEXTURE20                                    : constant := 16#84D4#;
 GL_TEXTURE21                                    : constant := 16#84D5#;
 GL_TEXTURE22                                    : constant := 16#84D6#;
 GL_TEXTURE23                                    : constant := 16#84D7#;
 GL_TEXTURE24                                    : constant := 16#84D8#;
 GL_TEXTURE25                                    : constant := 16#84D9#;
 GL_TEXTURE26                                    : constant := 16#84DA#;
 GL_TEXTURE27                                    : constant := 16#84DB#;
 GL_TEXTURE28                                    : constant := 16#84DC#;
 GL_TEXTURE29                                    : constant := 16#84DD#;
 GL_TEXTURE30                                    : constant := 16#84DE#;
 GL_TEXTURE31                                    : constant := 16#84DF#;
 GL_ACTIVE_TEXTURE                               : constant := 16#84E0#;
 GL_MAX_RENDERBUFFER_SIZE                        : constant := 16#84E8#;
 GL_INCR_WRAP                                    : constant := 16#8507#;
 GL_DECR_WRAP                                    : constant := 16#8508#;
 GL_TEXTURE_CUBE_MAP                             : constant := 16#8513#;
 GL_TEXTURE_BINDING_CUBE_MAP                     : constant := 16#8514#;
 GL_TEXTURE_CUBE_MAP_POSITIVE_X                  : constant := 16#8515#;
 GL_TEXTURE_CUBE_MAP_NEGATIVE_X                  : constant := 16#8516#;
 GL_TEXTURE_CUBE_MAP_POSITIVE_Y                  : constant := 16#8517#;
 GL_TEXTURE_CUBE_MAP_NEGATIVE_Y                  : constant := 16#8518#;
 GL_TEXTURE_CUBE_MAP_POSITIVE_Z                  : constant := 16#8519#;
 GL_TEXTURE_CUBE_MAP_NEGATIVE_Z                  : constant := 16#851A#;
 GL_MAX_CUBE_MAP_TEXTURE_SIZE                    : constant := 16#851C#;
 GL_VERTEX_ATTRIB_ARRAY_ENABLED                  : constant := 16#8622#;
 GL_VERTEX_ATTRIB_ARRAY_SIZE                     : constant := 16#8623#;
 GL_VERTEX_ATTRIB_ARRAY_STRIDE                   : constant := 16#8624#;
 GL_VERTEX_ATTRIB_ARRAY_TYPE                     : constant := 16#8625#;
 GL_CURRENT_VERTEX_ATTRIB                        : constant := 16#8626#;
 GL_VERTEX_ATTRIB_ARRAY_POINTER                  : constant := 16#8645#;
 GL_NUM_COMPRESSED_TEXTURE_FORMATS               : constant := 16#86A2#;
 GL_COMPRESSED_TEXTURE_FORMATS                   : constant := 16#86A3#;
 GL_BUFFER_SIZE                                  : constant := 16#8764#;
 GL_BUFFER_USAGE                                 : constant := 16#8765#;
 GL_STENCIL_BACK_FUNC                            : constant := 16#8800#;
 GL_STENCIL_BACK_FAIL                            : constant := 16#8801#;
 GL_STENCIL_BACK_PASS_DEPTH_FAIL                 : constant := 16#8802#;
 GL_STENCIL_BACK_PASS_DEPTH_PASS                 : constant := 16#8803#;
 GL_BLEND_EQUATION_ALPHA                         : constant := 16#883D#;
 GL_MAX_VERTEX_ATTRIBS                           : constant := 16#8869#;
 GL_VERTEX_ATTRIB_ARRAY_NORMALIZED               : constant := 16#886A#;
 GL_MAX_TEXTURE_IMAGE_UNITS                      : constant := 16#8872#;
 GL_ARRAY_BUFFER                                 : constant := 16#8892#;
 GL_ELEMENT_ARRAY_BUFFER                         : constant := 16#8893#;
 GL_ARRAY_BUFFER_BINDING                         : constant := 16#8894#;
 GL_ELEMENT_ARRAY_BUFFER_BINDING                 : constant := 16#8895#;
 GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING           : constant := 16#889F#;
 GL_STREAM_DRAW                                  : constant := 16#88E0#;
 GL_STATIC_DRAW                                  : constant := 16#88E4#;
 GL_DYNAMIC_DRAW                                 : constant := 16#88E8#;
 GL_FRAGMENT_SHADER                              : constant := 16#8B30#;
 GL_VERTEX_SHADER                                : constant := 16#8B31#;
 GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS               : constant := 16#8B4C#;
 GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS             : constant := 16#8B4D#;
 GL_SHADER_TYPE                                  : constant := 16#8B4F#;
 GL_FLOAT_VEC2                                   : constant := 16#8B50#;
 GL_FLOAT_VEC3                                   : constant := 16#8B51#;
 GL_FLOAT_VEC4                                   : constant := 16#8B52#;
 GL_INT_VEC2                                     : constant := 16#8B53#;
 GL_INT_VEC3                                     : constant := 16#8B54#;
 GL_INT_VEC4                                     : constant := 16#8B55#;
 GL_BOOL                                         : constant := 16#8B56#;
 GL_BOOL_VEC2                                    : constant := 16#8B57#;
 GL_BOOL_VEC3                                    : constant := 16#8B58#;
 GL_BOOL_VEC4                                    : constant := 16#8B59#;
 GL_FLOAT_MAT2                                   : constant := 16#8B5A#;
 GL_FLOAT_MAT3                                   : constant := 16#8B5B#;
 GL_FLOAT_MAT4                                   : constant := 16#8B5C#;
 GL_SAMPLER_2D                                   : constant := 16#8B5E#;
 GL_SAMPLER_CUBE                                 : constant := 16#8B60#;
 GL_DELETE_STATUS                                : constant := 16#8B80#;
 GL_COMPILE_STATUS                               : constant := 16#8B81#;
 GL_LINK_STATUS                                  : constant := 16#8B82#;
 GL_VALIDATE_STATUS                              : constant := 16#8B83#;
 GL_INFO_LOG_LENGTH                              : constant := 16#8B84#;
 GL_ATTACHED_SHADERS                             : constant := 16#8B85#;
 GL_ACTIVE_UNIFORMS                              : constant := 16#8B86#;
 GL_ACTIVE_UNIFORM_MAX_LENGTH                    : constant := 16#8B87#;
 GL_SHADER_SOURCE_LENGTH                         : constant := 16#8B88#;
 GL_ACTIVE_ATTRIBUTES                            : constant := 16#8B89#;
 GL_ACTIVE_ATTRIBUTE_MAX_LENGTH                  : constant := 16#8B8A#;
 GL_SHADING_LANGUAGE_VERSION                     : constant := 16#8B8C#;
 GL_CURRENT_PROGRAM                              : constant := 16#8B8D#;
 GL_IMPLEMENTATION_COLOR_READ_TYPE               : constant := 16#8B9A#;
 GL_IMPLEMENTATION_COLOR_READ_FORMAT             : constant := 16#8B9B#;
 GL_STENCIL_BACK_REF                             : constant := 16#8CA3#;
 GL_STENCIL_BACK_VALUE_MASK                      : constant := 16#8CA4#;
 GL_STENCIL_BACK_WRITEMASK                       : constant := 16#8CA5#;
 GL_FRAMEBUFFER_BINDING                          : constant := 16#8CA6#;
 GL_RENDERBUFFER_BINDING                         : constant := 16#8CA7#;
 GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE           : constant := 16#8CD0#;
 GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME           : constant := 16#8CD1#;
 GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL         : constant := 16#8CD2#;
 GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE : constant := 16#8CD3#;
 GL_FRAMEBUFFER_COMPLETE                         : constant := 16#8CD5#;
 GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT            : constant := 16#8CD6#;
 GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT    : constant := 16#8CD7#;
 GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS            : constant := 16#8CD9#;
 GL_FRAMEBUFFER_UNSUPPORTED                      : constant := 16#8CDD#;
 GL_COLOR_ATTACHMENT0                            : constant := 16#8CE0#;
 GL_DEPTH_ATTACHMENT                             : constant := 16#8D00#;
 GL_STENCIL_ATTACHMENT                           : constant := 16#8D20#;
 GL_FRAMEBUFFER                                  : constant := 16#8D40#;
 GL_RENDERBUFFER                                 : constant := 16#8D41#;
 GL_RENDERBUFFER_WIDTH                           : constant := 16#8D42#;
 GL_RENDERBUFFER_HEIGHT                          : constant := 16#8D43#;
 GL_RENDERBUFFER_INTERNAL_FORMAT                 : constant := 16#8D44#;
 GL_STENCIL_INDEX8                               : constant := 16#8D48#;
 GL_RENDERBUFFER_RED_SIZE                        : constant := 16#8D50#;
 GL_RENDERBUFFER_GREEN_SIZE                      : constant := 16#8D51#;
 GL_RENDERBUFFER_BLUE_SIZE                       : constant := 16#8D52#;
 GL_RENDERBUFFER_ALPHA_SIZE                      : constant := 16#8D53#;
 GL_RENDERBUFFER_DEPTH_SIZE                      : constant := 16#8D54#;
 GL_RENDERBUFFER_STENCIL_SIZE                    : constant := 16#8D55#;
 GL_RGB565                                       : constant := 16#8D62#;
 GL_LOW_FLOAT                                    : constant := 16#8DF0#;
 GL_MEDIUM_FLOAT                                 : constant := 16#8DF1#;
 GL_HIGH_FLOAT                                   : constant := 16#8DF2#;
 GL_LOW_INT                                      : constant := 16#8DF3#;
 GL_MEDIUM_INT                                   : constant := 16#8DF4#;
 GL_HIGH_INT                                     : constant := 16#8DF5#;
 GL_SHADER_BINARY_FORMATS                        : constant := 16#8DF8#;
 GL_NUM_SHADER_BINARY_FORMATS                    : constant := 16#8DF9#;
 GL_SHADER_COMPILER                              : constant := 16#8DFA#;
 GL_MAX_VERTEX_UNIFORM_VECTORS                   : constant := 16#8DFB#;
 GL_MAX_VARYING_VECTORS                          : constant := 16#8DFC#;
 GL_MAX_FRAGMENT_UNIFORM_VECTORS                 : constant := 16#8DFD#;


end;
